gunzip -c c_elegans.genomic.fa.gz | grep -o -E  'a' | wc -l >> celegans_data.txt
gunzip -c c_elegans.genomic.fa.gz | grep -o -E  't' | wc -l >> celegans_data.txt
gunzip -c c_elegans.genomic.fa.gz | grep -o -E  'c' | wc -l >> celegans_data.txt
gunzip -c c_elegans.genomic.fa.gz | grep -o -E  'g' | wc -l >> celegans_data.txt
gunzip -c c_elegans.genomic.fa.gz | grep -o -E  'a|t|c|g' | wc -l >> celegans_data.txt
gunzip -c c_elegans.genomic.fa.gz | grep -o -E  'at' | wc -l >> celegans_data.txt
gunzip -c c_elegans.genomic.fa.gz | grep -o -E  'ac' | wc -l >> celegans_data.txt
gunzip -c c_elegans.genomic.fa.gz | grep -o -E  'ag' | wc -l >> celegans_data.txt
gunzip -c c_elegans.genomic.fa.gz | grep -o -E  'aa' | wc -l >> celegans_data.txt
gunzip -c c_elegans.genomic.fa.gz | grep -o -E  'ta' | wc -l >> celegans_data.txt
gunzip -c c_elegans.genomic.fa.gz | grep -o -E  'tc' | wc -l >> celegans_data.txt
gunzip -c c_elegans.genomic.fa.gz | grep -o -E  'tg' | wc -l >> celegans_data.txt
gunzip -c c_elegans.genomic.fa.gz | grep -o -E  'tt' | wc -l >> celegans_data.txt
gunzip -c c_elegans.genomic.fa.gz | grep -o -E  'ca' | wc -l >> celegans_data.txt
gunzip -c c_elegans.genomic.fa.gz | grep -o -E  'ct' | wc -l >> celegans_data.txt
gunzip -c c_elegans.genomic.fa.gz | grep -o -E  'cg' | wc -l >> celegans_data.txt
gunzip -c c_elegans.genomic.fa.gz | grep -o -E  'cc' | wc -l >> celegans_data.txt
gunzip -c c_elegans.genomic.fa.gz | grep -o -E  'ga' | wc -l >> celegans_data.txt
gunzip -c c_elegans.genomic.fa.gz | grep -o -E  'gt' | wc -l >> celegans_data.txt
gunzip -c c_elegans.genomic.fa.gz | grep -o -E  'gc' | wc -l >> celegans_data.txt
gunzip -c c_elegans.genomic.fa.gz | grep -o -E  'gg' | wc -l >> celegans_data.txt
